# Generated by Django 4.2 on 2023-08-30 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import point_cloud_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование подкласса')),
                ('cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_cloud_app.class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Подкласс',
                'verbose_name_plural': 'Подклассы',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название объекта')),
                ('length', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Длина объекта')),
                ('width', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Ширина объекта')),
                ('height', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Высота объекта')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время формирования')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('file', models.FileField(upload_to='', validators=[point_cloud_app.validators.validate_is_las], verbose_name='Файл')),
                ('num', models.CharField(default='0', max_length=5, verbose_name='Номер аудитории')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('subcl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point_cloud_app.subclass', verbose_name='Подкласс')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
